obj-y                                   += board-mapphone.o \
                                           board-mapphone-camera.o \
                                           board-mapphone-flash.o \
                                           board-mapphone-padconf.o \
                                           board-mapphone-panel.o \
                                           board-mapphone-spi.o \
                                           board-mapphone-cpcap-client.o \
                                           board-mapphone-sensors.o \
                                           board-mapphone-hsmmc.o \
                                           board-mapphone-keypad.o \
                                           board-mapphone-wifi.o \
                                           board-mapphone-gpio.o \
                                           board-mapphone-modem.o \
                                           board-mapphone-mmcprobe.o

